### ISSUE TITLE
The flexiv_moveit_config package cannot be opened using the moveit setup assisstant.

### ISSUE THREAD

**Issue by acf986** [flexivrobotics/flexiv_ros#5]
Hi,
It seems the flexiv_moveit_config package cannot be opened using the moveit setup assisstant.
The reason being there is some error in the srdf file:
```

Undefined substitution argument name
when processing file: /WorkSpace/moveit_ws/src/flexiv_ros1/flexiv_moveit_config/config/rizon.srdf.xacro
[ERROR] [1679296237.513101935]: Could not parse the SRDF XML File. Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=15 (0xf) Line number=0

```

**Comment by munseng-flexiv** [comment]
Hello,

the bug is fixed with the PR #6 and merged into the `develop` branch

You can check out the `develop` branch and see if there is still an error.
