### ISSUE TITLE
Arm drops while using the "joint_impedance_controller"

### ISSUE THREAD

**Issue by acf986** [flexivrobotics/flexiv_ros#8]
The robot arm drops while using the "joint_impedance_controller".
The joint impedance controller is turned on by modifying the line 7 of rizon_control.launch

Then I use the following code to publish the joint position and joint velocity reference to the topic "/joint_impedance_controller/command"
```
void ArmControl::flexiv_execute_trajectory(const robot_trajectory::RobotTrajectory& trajectory)
{
  for (int i=0; i<trajectory.getWayPointCount(); i++)
  {
    std::cout<<i<<std::endl;
    flexiv_msgs::JointPosVel msg;
    moveit::core::RobotState wp = trajectory.getWayPoint(i);

    for (int j=0; j<7 ;j++)
    {
      std::string joint_name = "joint"+std::to_string(j+1);
      msg.positions[j] = wp.getVariablePosition(joint_name);
      msg.velocities[j] = wp.getVariableVelocity(joint_name);
    }

    command_pub_.publish(msg);
    std::this_thread::sleep_for(std::chrono::milliseconds(33));
  }
  //std::this_thread::sleep_for(std::chrono::milliseconds(1000));
}
```
The publishing rate is 30 Hz.

**Comment by acf986** [comment]
The published trajectory started with the current joint position and 0 joint velocities.
The published trajectory satisfies an acceleration limit of 2.25 rad/s^2 on each joint.

**Comment by acf986** [comment]
After digging into it for a while, I found the reason for the drop is because there's a "constant shift" or "constant trim" between the given joint reference and the robot's actual joint position. 
Therefore, when you set the joint reference to the current measured joint position. The robot's actual joint position will go to the "reference + trim" value. Since now "reference = current measurement", the robot arm will appear it is dropping.

**Comment by acf986** [comment]
I have modified the JointImpedanceController::update function to print out the joint position error like the following:

```
void JointImpedanceController::update(
    const ros::Time& /*time*/, const ros::Duration& /*period*/)
{
    command_struct_ = *(command_.readFromRT());

    static int ctt = 0;
    ctt++;
    if (ctt%100 == 0)
    {
      std::cout<<"joint error: ";
    }
    for (std::size_t i = 0; i < num_joints_; ++i) {
        // Get current joint positions and velocities
        double q = joints_[i].getPosition();
        double dq = joints_[i].getVelocity();

        // Get target positions and velocities
        double q_des = command_struct_.positions_[i];
        double dq_des = 0;
        if (command_struct_.has_velocity_) {
            dq_des = command_struct_.velocities_[i];
        }

        enforceJointLimits(i, q_des);

        if (ctt%100 == 0)
        {
          std::cout<<(q_des - q)<<", ";
        }

        // Compute torque
        double tau = k_p_[i] * (q_des - q) + k_d_[i] * (dq_des - dq);
        joints_[i].setCommand(tau);
    }

    if (ctt%100 == 0)
    {
      std::cout<<std::endl;
    }
}
```
To prevent the printing take too much time and affect the control, it only prints at 10Hz.

As long as I send any reference to the controller (in this case, I send a constant value that is very close to the current measurement), a steady state tracking error occurs (these errors are taken when the robot comes to a steady state):

```
joint error: -0.0101972, 0.00437606, -0.000312181, -0.0920779, 0.00229139, -0.0165077, 0.0015217, 
joint error: -0.0101943, 0.00437676, -0.000310329, -0.0920794, 0.00229272, -0.0165098, 0.00152351, 
joint error: -0.0101974, 0.00437664, -0.000312507, -0.0920778, 0.00229036, -0.0165111, 0.00152065, 
joint error: -0.0101976, 0.00437852, -0.000311569, -0.0920765, 0.00228969, -0.0165055, 0.00152035, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
joint error: -0.0101976, 0.00437505, -0.000311155, -0.0920771, 0.00228918, -0.0165092, 0.00152143, 
```
The unit is in radius, and the error are quite big for a robot arm? Especially Joint 4 and 6, more than 5 degree.

**Comment by acf986** [comment]
Hi, the bug turns out to be on the line 103 of the `joint_impedance_controller.cpp`
`command_struct_.velocities_[i] = pos_command[i];`
where you assigned the `pos_command` to velocity reference, I have changed it back to `vel_command` and everything now works.

**Comment by munseng-flexiv** [comment]
> Hi, the bug turns out to be on the line 103 of the joint_impedance_controller.cpp
> 
> `command_struct_.velocities_[i] = pos_command[i];`
> 
> where you assigned the pos_command to velocity reference, I have changed it back to vel_command and everything now works.

Thanks for your help finding the bug! I will create a PR asap for the bugfix. Great that it works as intended.
